### ISSUE TITLE
Costrutture di DFSCrawler

### ISSUE THREAD

**Issue by iannellog** [Domenico2020/Analisi-URL#10]
Per come è pensata la classe, i parametri list_of_links e list_of_cycles devono essere inizializzate sempre a liste vuote.
Non ha quindi senso indicare dei valori di default (tra l'altro ho visto si un sito che usare come default il simbolo [] può creare dei problemi). E' preferibile non indicare valori di default, ma inizializzare gli attributi dell'oggetto a liste vuote nell costruttore.

**Comment by Egidio92** [comment]
Ho inizializzato le liste vuote list_of_links e list_of_cycles nel costruttore.
