### ISSUE TITLE
opzione sulla profondità

### ISSUE THREAD

**Issue by iannellog** [Domenico2020/Analisi-URL#4]
E' bene che l'utente possa indicare attraverso un'opzione la profondità massima a cui arrivare nella ricerca con un default piccolo (per es. 2 o 3).

**Comment by Egidio92** [comment]
Buonpomeriggio Professore ho aggiunto nel parser le opzioni relative sia per la profondità massima a cui arrivare (max_depth) che per quella da cui partire (depth). Nel codice ho impostato dei default.

**Comment by iannellog** [comment]
Mi sembra che l'opzione --depth non abbia molto senso. 
Se gli passo un valore diverso da 0 (per es. -d 1) che succede? Ho fatto qualche prova e in un caso si è generato un errore.
O date un senso chiaro all'opzione -d (e senza generare errori) oppure eliminatela.

**Comment by Egidio92** [comment]
Ho deciso di eliminare l'opzione "depth"
