### ISSUE TITLE
ristrutturare il codice

### ISSUE THREAD

**Issue by iannellog** [Domenico2020/Analisi-URL#5]
Conviene che ogni file contenga una parte del codice che ha una sua indipendenza dal resto evitando file troppo lunghi.
Per esempio il file che contiene il main conviene che non abbia il main troppo in fondo e troppo lontano dal codice che descrive l'interfaccia utente (per esempio le opzioni da linea di comando) perché altrimenti diventa difficile leggere il codice.

**Comment by Egidio92** [comment]
Professore questa issues penso sia stata risolta
