### ISSUE TITLE
eliminare il metodo get_links

### ISSUE THREAD

**Issue by iannellog** [Domenico2020/Analisi-URL#6]
la gestione del carattere '\n' e simili deve essere svolta da TXTReader

**Comment by iannellog** [comment]
eliminare le variabili globali

**Comment by Egidio92** [comment]
"la gestione del carattere '\n' e simili" è stata risolta ma ho difficolta nell'eliminare la variabile globale "list_of_links"

**Comment by Egidio92** [comment]
Comunque è stato eliminato il metodo get_links

**Comment by iannellog** [comment]
Anche le classi DFSCrawler, ListCleaner devono essere messe in un file separato. 
Se lo fate le variabili url e list_of_links non possono essere più globali  e dovete gestirle in un altro modo.
Se non vi è chiaro come, dobbiamo incontrarci o fare una call (ma preferirei di persona perché mi pare che sia il caso di andare più a fondo).

**Comment by Egidio92** [comment]
Professore penso di essere riuscito a suddividere opportunamente il file. Le classi DFSCrawler e ListCleaner sono state messe rispettivamente in crawler.py ed in cleaner.py
