### ISSUE TITLE
Eliminare entry nella lista di uscita che non sono url

### ISSUE THREAD

**Issue by iannellog** [Domenico2020/Analisi-URL#7]
Nella lista di uscita compaiono entri che non sono url. Di seguito un pezzo del vostro caso di test:

>    "i link fanno riferimento a: http://www.sialserramentisrl.it",
>    "index.html",
>    "about.html",
>    "services.html",
>    "work.html",
>    "agevolazionifiscali.html",
>    "blog.html",
>    "contact.html",
>    "https://it-it.facebook.com/www.SialSerramenti/",
>    "https://www.instagram.com/sialserramenti/",
>    "profili.html",
>    "porteinterne.html",
>    "fotopersiana.html",
>    "vetristrutturali.html",
>    "accessori.html",
>    "showroom.html",
>    "mailto:info@sialserramentisrl.it",
>    "tel://",

Dovete gestire in modo più accurato l'inserimento di entry nella lista. Considerare tutti i casi forse è troppo complicato, ma almeno quelli più frequenti vanno presi in considerazione. Ho provato a far girare il mio crawler (che ha un output leggermente diverso dal vostro e che non dovete per forza replicare) sulla vostra lista con lo stesso livello di profondità. In allegato il risultato che vi può servire da ulteriore test.

[my_test.json.zip](https://github.com/Domenico2020/Analisi-URL/files/5898389/my_test.json.zip)

**Comment by Egidio92** [comment]
È stato gestito meglio l'inserimento di entry nella lista. In particolare, i link alla mail ed al telefono non sono stati considerati. Tutti i link relativi sono stati resi assoluti.
